import { GoogleAuth } from 'google-auth-library';
import { Storage } from '@google-cloud/storage';

export interface ImageGenerationOptions {
    prompt: string;
    aspectRatio?: '1:1' | '9:16' | '16:9' | '4:5';
    negativePrompt?: string;
    style?: 'realistic' | 'professional' | 'casual' | 'lifestyle';
}

export class ImageGenerator {
    private projectId: string;
    private location: string;
    private auth: GoogleAuth;
    private storage: Storage;
    private bucketName: string;

    constructor() {
        this.projectId = process.env.GOOGLE_CLOUD_PROJECT_ID || '';
        this.location = process.env.GOOGLE_CLOUD_LOCATION || 'us-central1';
        this.bucketName = process.env.GCS_BUCKET_NAME || '';

        this.auth = new GoogleAuth({
            scopes: ['https://www.googleapis.com/auth/cloud-platform']
        });

        this.storage = new Storage({
            projectId: this.projectId
        });
    }

    /**
     * Generar imagen con Vertex AI Imagen 3
     */
    async generate(options: ImageGenerationOptions): Promise<string> {
        console.log('[ImageGenerator] 🎨 Generando imagen con Vertex AI...');

        try {
            const client = await this.auth.getClient();
            const token = await client.getAccessToken();

            if (!token.token) {
                throw new Error('No access token available');
            }

            const enhancedPrompt = this.enhancePrompt(options.prompt, options.style);

            const url = `https://${this.location}-aiplatform.googleapis.com/v1/projects/${this.projectId}/locations/${this.location}/publishers/google/models/imagen-3.0-generate-001:predict`;

            console.log('[ImageGenerator] Calling Vertex AI Imagen 3...');

            const response = await fetch(url, {
                method: 'POST',
                headers: {
                    'Authorization': `Bearer ${token.token}`,
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({
                    instances: [{ prompt: enhancedPrompt }],
                    parameters: {
                        sampleCount: 1,
                        aspectRatio: options.aspectRatio || '9:16',
                        negativePrompt: options.negativePrompt || 'cartoon, anime, illustration, blurry, low quality, text, watermark',
                        safetySetting: 'block_few',
                        personGeneration: 'allow_all'
                    }
                })
            });

            if (!response.ok) {
                const errorText = await response.text();
                throw new Error(`Vertex AI error: ${response.status} - ${errorText}`);
            }

            const data = await response.json();
            const base64 = data.predictions?.[0]?.bytesBase64Encoded;

            if (!base64) {
                throw new Error('No image generated by Vertex AI');
            }

            console.log('[ImageGenerator] ✅ Image generated, uploading to GCS...');

            // Upload to GCS
            const publicUrl = await this.uploadToStorage(base64);

            console.log('[ImageGenerator] ✅ Complete:', publicUrl);

            return publicUrl;

        } catch (error) {
            console.error('[ImageGenerator] ❌ Error:', error);
            throw error;
        }
    }

    /**
     * Generar múltiples imágenes en paralelo (batch)
     */
    async generateBatch(optionsArray: ImageGenerationOptions[]): Promise<string[]> {
        console.log(`[ImageGenerator] 📸 Generando ${optionsArray.length} imágenes en batch...`);

        const startTime = Date.now();
        const promises = optionsArray.map(opts => this.generate(opts));
        const results = await Promise.allSettled(promises);

        const successful = results
            .filter((r): r is PromiseFulfilledResult<string> => r.status === 'fulfilled')
            .map(r => r.value);

        const failed = results.filter(r => r.status === 'rejected').length;

        const duration = ((Date.now() - startTime) / 1000).toFixed(1);
        console.log(`[ImageGenerator] ✅ Batch complete: ${successful.length} success, ${failed} failed in ${duration}s`);

        return successful;
    }

    private enhancePrompt(base: string, style?: ImageGenerationOptions['style']): string {
        const styleMap = {
            realistic: 'hyper-realistic photograph, professional photography, 8K quality, magazine quality',
            professional: 'professional studio photograph, corporate style, clean lighting, sharp focus',
            casual: 'natural candid photograph, authentic moment, natural lighting, lifestyle',
            lifestyle: 'lifestyle photography, aspirational, high-end magazine quality, elegant'
        };

        const styleText = style ? styleMap[style] : styleMap.realistic;
        return `${base}, ${styleText}, sharp focus, detailed, high quality, professional`;
    }

    private async uploadToStorage(base64: string): Promise<string> {
        const filename = `images/${Date.now()}_${Math.random().toString(36).substr(2, 9)}.png`;
        const buffer = Buffer.from(base64, 'base64');

        try {
            const bucket = this.storage.bucket(this.bucketName);
            const file = bucket.file(filename);

            await file.save(buffer, {
                metadata: {
                    contentType: 'image/png',
                    cacheControl: 'public, max-age=31536000'
                }
            });

            // Make public
            await file.makePublic();

            return `https://storage.googleapis.com/${this.bucketName}/${filename}`;

        } catch (error) {
            console.error('[ImageGenerator] Upload error:', error);
            throw new Error(`Failed to upload to GCS: ${error}`);
        }
    }

    /**
     * Calcular costo de generación
     */
    calculateCost(count: number = 1): number {
        // Vertex AI Imagen 3: ~$0.02 per image
        return count * 0.02;
    }
}
