import { NextRequest, NextResponse } from 'next/server';
import { GmailOAuthService } from '@/lib/gmail-oauth-service';
import { agentDispatcher } from '@/lib/agents/agent-dispatcher';

export const runtime = 'nodejs';

/**
 * GET — Listar correos del buzón
 * Query params: q (Gmail search query), max (maxResults)
 * Header: X-Store-Id
 *
 * Ejemplos:
 *   GET /api/communications/gmail?q=is:unread&max=10
 *   GET /api/communications/gmail?q=from:cliente@gmail.com
 */
export async function GET(req: NextRequest) {
    try {
        const storeId = req.headers.get('X-Store-Id') || req.nextUrl.searchParams.get('storeId');
        const query   = req.nextUrl.searchParams.get('q') || 'is:unread';
        const max     = parseInt(req.nextUrl.searchParams.get('max') || '20');

        if (!storeId) return NextResponse.json({ error: 'storeId requerido' }, { status: 400 });

        const emails = await GmailOAuthService.listEmails(storeId, { query, maxResults: max });
        return NextResponse.json({ ok: true, emails, total: emails.length });

    } catch (e: any) {
        console.error('[Gmail GET]', e.message);
        return NextResponse.json({ error: e.message }, { status: 500 });
    }
}

/**
 * POST — El agente genera y envía respuesta automática a un correo
 * Body: { messageId, threadId, from, subject, body, autoReply? }
 * Header: X-Store-Id
 *
 * Si autoReply=true, el agente IA genera la respuesta.
 * Si autoReply=false (o no enviado), se usa el campo `body` como respuesta directa.
 */
export async function POST(req: NextRequest) {
    try {
        const storeId = req.headers.get('X-Store-Id');
        const body = await req.json();
        const {
            messageId,
            threadId,
            from,
            subject,
            body: emailBody,
            autoReply = false
        } = body;

        if (!storeId || !messageId) {
            return NextResponse.json({ error: 'storeId (header) y messageId (body) son requeridos' }, { status: 400 });
        }

        let replyHtml = emailBody;

        // Si autoReply=true, el agente IA genera la respuesta
        if (autoReply) {
            const result = await agentDispatcher.dispatch({
                role: 'ops-commander',
                storeId,
                prompt: `Redacta una respuesta profesional y empática a este correo de cliente.

De: ${from}
Asunto: ${subject}
Mensaje del cliente:
${emailBody}

Instrucciones:
- Genera SOLO el cuerpo del email en HTML válido (sin asunto ni cabeceras)
- Tono: profesional, cálido, resolutivo
- Resuelve la consulta directamente si tienes contexto suficiente
- Si no tienes suficiente contexto, solicita más información amablemente
- Firma como "Equipo de Atención al Cliente"
- Idioma: mismo que el correo del cliente`,
            });
            replyHtml = result.text;
        }

        if (!replyHtml) {
            return NextResponse.json({ error: 'No hay cuerpo de respuesta (replyHtml vacío)' }, { status: 400 });
        }

        const sent = await GmailOAuthService.replyToEmail(storeId, {
            threadId,
            messageId,
            to: from,
            subject,
            bodyHtml: replyHtml
        });

        return NextResponse.json({ ok: true, sent, autoGenerated: autoReply });

    } catch (e: any) {
        console.error('[Gmail POST]', e.message);
        return NextResponse.json({ error: e.message }, { status: 500 });
    }
}

/**
 * PATCH — Operaciones sobre un correo (marcar leído, etc.)
 * Body: { messageId, action: 'markAsRead' }
 */
export async function PATCH(req: NextRequest) {
    try {
        const storeId = req.headers.get('X-Store-Id');
        const { messageId, action } = await req.json();

        if (!storeId || !messageId || !action) {
            return NextResponse.json({ error: 'storeId, messageId y action son requeridos' }, { status: 400 });
        }

        if (action === 'markAsRead') {
            await GmailOAuthService.markAsRead(storeId, messageId);
            return NextResponse.json({ ok: true, action });
        }

        return NextResponse.json({ error: `Acción desconocida: ${action}` }, { status: 400 });

    } catch (e: any) {
        console.error('[Gmail PATCH]', e.message);
        return NextResponse.json({ error: e.message }, { status: 500 });
    }
}
